alter table SALESCAFE_ORDER add constraint FK_SALESCAFE_ORDER_WORK_DAY foreign key (WORK_DAY_ID) references SALESCAFE_WORK_DAY(ID);
create index IDX_SALESCAFE_ORDER_WORK_DAY on SALESCAFE_ORDER (WORK_DAY_ID);
