-- begin SALESCAFE_ORDER_CARD
alter table SALESCAFE_ORDER_CARD add constraint FK_SALESCAFE_ORDER_CARD_PRODUCT foreign key (PRODUCT_ID) references SALESCAFE_PRODUCT(ID)^
alter table SALESCAFE_ORDER_CARD add constraint FK_SALESCAFE_ORDER_CARD_ORDER foreign key (ORDER_ID) references SALESCAFE_ORDER(ID)^
create index IDX_SALESCAFE_ORDER_CARD_PRODUCT on SALESCAFE_ORDER_CARD (PRODUCT_ID)^
create index IDX_SALESCAFE_ORDER_CARD_ORDER on SALESCAFE_ORDER_CARD (ORDER_ID)^
-- end SALESCAFE_ORDER_CARD
-- begin SALESCAFE_ORDER
alter table SALESCAFE_ORDER add constraint FK_SALESCAFE_ORDER_WORK_DAY foreign key (WORK_DAY_ID) references SALESCAFE_WORK_DAY(ID)^
create index IDX_SALESCAFE_ORDER_WORK_DAY on SALESCAFE_ORDER (WORK_DAY_ID)^
-- end SALESCAFE_ORDER
